# Site settings
email: "human@playbotparty.com"
baseurl: ""
paginate: 6
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Bot Party
description: A sound game to hold hands in. Bot Party is a physical sound game.
url: "http://www.playbotparty.com"
twitter_username: playbotparty
default_img: /images/social_1.jpg

# Profile settings
name: Bot Party
profile_img: /images/social_1.jpg
profile: Bot Party in an interactive sound experience for humans. Hold hands with other players to get the bot sound spectacular started! Game Design by Phoenix Perry, Sound Design by Freida Abtan, Magic by Helen Steer. 
social:
  github: https://github.com/phoenixperry/bot_party
  twitter: http://twitter.com/playbotparty
  instagram: https://www.instagram.com/bot.party/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
