# Site settings
email: "human@playbotparty.com"
baseurl: ""
paginate: 6
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Bot Party
description: A sound game to hold hands in. Bot Party is a physical sound game.
url: "http://www.playbotparty.com"
twitter_username: playbotparty
default_img: /images/social_1.jpg

# Profile settings
name: Bot Party
profile_img: /images/social_1.jpg
profile: Game Design by Phoenix Perry and Charlie Ann Page. Sound Engineering by Freida Abtan. Sound Design by Brian Jackson. Bot Development and AI Diplomatic Relations by Charlie Ann Page. Engineering by Phoenix Perry & Helen Steer. Jr Develeoper, Emily Roderick. Graphic Design by Mimi Sotudeh.  Magic by Helen Steer.
social:
  github: https://github.com/phoenixperry/bot_party
  twitter: http://twitter.com/playbotparty
  instagram: https://www.instagram.com/bot.party/
# Bot Party is part of a larger research project by Phoenix Perry into physical play, prosocial behavior through touch and intimacy.
# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
