# Site settings
email: "human@playbotparty.com"
baseurl: ""
paginate: 6
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Bot Party
description: A sound game to hold hands in. Bot Party is a physical sound creation game.
url: "http://www.playbotparty.com"
twitter_username: playbotparty
default_img: /images/social_1.jpg

# Profile settings
name: Bot Party
profile_img: /images/social_1.jpg
profile: Bot Party, a sound world to hold hands in. You can find us on twitter at @playbotparty
social: twitter
github: phoenixperry

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
